@startuml
'https://plantuml.com/sequence-diagram

class Main {
    + siteName: String
    + author: String
    + js: String
    + css: String

    + promptUserForInput()
    + printOutput()
}

class WebsiteGenerator {
    - path: String

    + createWebsite(siteName, author, js, css)
    + createHtml(path, siteName, author)
    if (js yes?) then (yes)
        + : createJSFile(path, js)
    if (css yes?) then (yes)
        + : createCSSFile(path, css)
}

Main --|> WebsiteGenerator
WebsiteGenerator o--> Main
@enduml