@startuml
'https://plantuml.com/class-diagram

class Main {
    + getFreq(): String
    + output: String = printFreq(sortByHighestFreq())
}

class FrequencyFinder {
    + counter: int

    + getFreq(): String
    + sortByHighestFreq(): TreeMap(<String>, <Integer>)
}

Main -|> FrequencyFinder
FrequencyFinder o-> Main
@enduml