@startuml
'https://plantuml.com/sequence-diagram

class Main {
    + names: ArrayList

    + scanNamesFromFile()
    + createOutputFile()
    + printToFile(sortedNames)
}

class Sort {
    + sortedNames: ArrayList
    
    + sortAlphabetically(names)
}

Main o--> Sort
Main <|-- Sort

@enduml