@startuml
'https://plantuml.com/sequence-diagram

class Main {
    + names: ArrayList
    + counter: int

    + scanNamesFromFile()
    + createOutputFile()
    + printToFile(sortedNames)
}

class Sort {
    + sortedNames: ArrayList

    + sortAlphabetically(names)
}

Main o--> Sort
Main <|-- Sort

@enduml