@startuml
'https://plantuml.com/class-diagram

class Main {
    + getFile()
}

class ReplaceWord {
    + getFile(): void
    + createOutFile(): string
    + printToOutput(): void
}

Main --|> ReplaceWord
Main <--o ReplaceWord
@enduml